services:
    - type: web
    name: smart-lender-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    autoDeploy: true
    plan: free